-- Seed completo tarifas 2026 desde catalogo_comercial_eas_2026.json
-- price_per_person = escala 1 pax (venta). Transporte/restaurante = 0 (paquete incluido en tarifa).
-- Para cotizar por #pax usa el JSON (priceScaleByPax); PG guarda referencia 1 pax.

INSERT INTO sig.tour_products (
    code, name, price_per_person, transport_per_person, restaurant_per_person, currency, keywords, active
) VALUES
    ('RAFTING_EN_EL_EJE_CAFETERO', 'Rafting en el Eje Cafetero [PRIVADO]', 705000, 0, 0, 'COP', 'rafting,rio,eje cafetero', true),
    ('CABALGATA_ECOLOGICA', 'Cabalgata Ecológica [PRIVADO]', 906000, 0, 0, 'COP', 'cabalgata,caballo,ecologica', true),
    ('CANOPY_EXTREMO_EN_EL_QUINDIO', 'Canopy Extremo en el Quindío [PRIVADO]', 663000, 0, 0, 'COP', 'canopy,extremos,quindio', true),
    ('BICIRRIEL_EN_EL_QUINDIO', 'Bicirriel en el Quindío [PRIVADO]', 730000, 0, 0, 'COP', 'bicirriel,bici', true),
    ('GLOBO_AEROSTATICO', 'Globo Aerostático [PRIVADO]', 1253000, 0, 0, 'COP', 'globo,aerostatico,vuelo', true),
    ('PARAPENTE', 'Parapente [PRIVADO]', 825000, 0, 0, 'COP', 'parapente,vuelo', true),
    ('PARAMOTOR', 'Paramotor [PRIVADO]', 892000, 0, 0, 'COP', 'paramotor,paratrike,vuelo', true),
    ('SANTUARIO_DE_LA_PALMA_DE_CERA', 'Santuario de la Palma de Cera [PRIVADO]', 1079000, 0, 0, 'COP', 'santuario,palma de cera,carbonera', true),
    ('TREKKING_EN_RN_ACAIME', 'Trekking en RN Acaime [PRIVADO]', 611000, 0, 0, 'COP', 'trekking,acaime,reserva', true),
    ('SALENTO_Y_VALLE_DEL_COCORA', 'Salento y Valle del Cócora [PRIVADO]', 682000, 0, 0, 'COP', 'salento,cocora,valle', true),
    ('SALENTO_Y_VALLE_DEL_COCORA_MAS', 'Salento y Valle del Cócora más [PRIVADO]', 883000, 0, 0, 'COP', 'salento,cocora,plus', true),
    ('RECORRIDO_DEL_MONOAULLADOR', 'Recorrido del Mono Aullador [PRIVADO]', 578000, 0, 0, 'COP', 'mono aullador,kirakai', true),
    ('RUTA_PARQUE_DE_LA_VIDA', 'Ruta Parque de la Vida [PRIVADO]', 448000, 0, 0, 'COP', 'parque de la vida', true),
    ('RUTA_AVES_Y_CAFE', 'Ruta Aves y Café [PRIVADO]', 532000, 0, 0, 'COP', 'aves,cafe,birdwatching', true),
    ('RUTA_JARDIN_BOTANICO', 'Ruta Jardín Botánico [PRIVADO]', 561000, 0, 0, 'COP', 'jardin botanico,calarca', true),
    ('RUTA_GALLITO_DE_ROCA', 'Ruta Gallito de Roca [PRIVADO]', 607000, 0, 0, 'COP', 'gallito de roca,santa rita', true),
    ('RUTA_COCORA', 'Ruta Cócora [PRIVADO]', 526000, 0, 0, 'COP', 'ruta cocora', true),
    ('RUTA_RESERVA_ACAIME', 'Ruta Reserva Acaime [PRIVADO]', 607000, 0, 0, 'COP', 'reserva acaime', true),
    ('RUTA_CACIQUE_CALARCA', 'Ruta Cacique Calarcá [PRIVADO]', 756000, 0, 0, 'COP', 'cacique calarca,peñas blancas', true),
    ('RUTA_SUSURRO_DE_GUADUALES', 'Ruta Susurro de Guaduales [PRIVADO]', 513000, 0, 0, 'COP', 'guaduales,soñarte', true),
    ('RUTA_RESERVA_KIRAKAI', 'Ruta Reserva Kirakai [PRIVADO]', 557000, 0, 0, 'COP', 'kirakai', true),
    ('PIJAO_AVES_Y_COMUNIDAD', 'Pijao, aves y comunidad [PRIVADO]', 780000, 0, 0, 'COP', 'pijao,aves,comunidad', true),
    ('PARAMO_DE_CHILI', 'Páramo de Chili [PRIVADO]', 1062000, 0, 0, 'COP', 'paramo,chili', true),
    ('VOLCAN_EL_MACHIN', 'Volcán El Machín [PRIVADO]', 1756000, 0, 0, 'COP', 'volcan,machin', true),
    ('EXPEDICION_MURILLO', 'Expedición Murillo [PRIVADO]', 3632000, 0, 0, 'COP', 'murillo,expedicion,nevados', true),
    ('PLAN_PARQUE_LOS_NEVADOS', 'Plan Parque Los Nevados [PRIVADO]', 1691000, 0, 0, 'COP', 'parque nevados,nevados', true),
    ('SENDERISMO_PENAS_BLANCAS', 'Senderismo Peñas Blancas [PRIVADO]', 676000, 0, 0, 'COP', 'peñas blancas,senderismo,calarca', true),
    ('SENDERISMO_SANTA_RITA', 'Senderismo Santa Rita [PRIVADO]', 378000, 0, 0, 'COP', 'santa rita,senderismo', true),
    ('SENDERISMO_OTUN_QUIMBAYA', 'Senderismo Otún Quimbaya [PRIVADO]', 731000, 0, 0, 'COP', 'otun,quimbaya,senderismo', true),
    ('RECORRIDO_POR_LA_CORDILLERA', 'Recorrido por la Cordillera [PRIVADO]', 1400000, 0, 0, 'COP', 'cordillera,pijao', true),
    ('RECORRIDO_CAFETERO_CON_CATACION', 'Recorrido cafetero con catación [PRIVADO]', 917000, 0, 0, 'COP', 'cafetero,catacion,cafe', true),
    ('RECORRIDO_CAFETERO_TRADICIONAL', 'Recorrido cafetero tradicional [PRIVADO]', 599000, 0, 0, 'COP', 'cafetero tradicional,cafe,almuerzo', true),
    ('RECORRIDO_CAFETERO_TRADICIONAL_2', 'Recorrido cafetero tradicional (alt.) [PRIVADO]', 488000, 0, 0, 'COP', 'cafetero tradicional,alternativa', true),
    ('RECORRIDO_LA_GUAYABA', 'Recorrido la Guayaba [PRIVADO]', 948000, 0, 0, 'COP', 'guayaba', true),
    ('PROGRAMA_DE_CACAO', 'Programa de Cacao [PRIVADO]', 662000, 0, 0, 'COP', 'cacao,chocolate', true),
    ('METODOS_DE_FILTRADO', 'Métodos de Filtrado [PRIVADO]', 759000, 0, 0, 'COP', 'filtrado,cafe,metodos', true),
    ('PROGRAMA_DE_PERMACULTURA', 'Programa de Permacultura [PRIVADO]', 954000, 0, 0, 'COP', 'permacultura,mama lulu,quimbaya', true),
    ('CREA_TU_PROPIO_SOUVENIR', 'Crea tu propio souvenir [PRIVADO]', 691000, 0, 0, 'COP', 'souvenir,taller,arte', true),
    ('CITY_TOUR_POR_SALENTO', 'City tour por Salento [PRIVADO]', 923000, 0, 0, 'COP', 'city tour,salento', true),
    ('PROGRAMA_DE_CESTERIA_EN_FILANDIA', 'Programa de cestería en Filandia [PRIVADO]', 1089000, 0, 0, 'COP', 'cesteria,filandia,bejuco', true),
    ('TALLER_DE_COCINA_DE_AUTOR', 'Taller de cocina de autor [PRIVADO]', 1402000, 0, 0, 'COP', 'cocina,taller,autor', true),
    ('BARISTA_POR_UN_DIA', 'Barista por un día [PRIVADO]', 1402000, 0, 0, 'COP', 'barista,cafe', true),
    ('FILANDIA_SALENTO_Y_VALLE_DE_COCORA', 'Filandia, Salento y Valle de Cócora [PRIVADO]', 1177000, 0, 0, 'COP', 'filandia,salento,cocora,combo', true),
    ('PROGRAMA_DE_CACAO_POPORO', 'Programa de Cacao + Poporo [PRIVADO]', 986000, 0, 0, 'COP', 'cacao,poporo,quimbaya', true),
    ('CITYTOUR_SALENTO_COMP', 'Citytour Salento [COMPARTIDO]', 364000, 0, 0, 'COP', 'citytour,salento,compartido', true),
    ('SANTA_RITA_PRINCIPIANTES_COMP', 'Santa Rita - Principiantes [COMPARTIDO]', 550000, 0, 0, 'COP', 'santa rita,principiantes,compartido', true),
    ('INTERPRETACION_PALMA_DE_CERA_COMP', 'Interpretación Palma de Cera [COMPARTIDO]', 154000, 0, 0, 'COP', 'palma de cera,interpretacion,compartido', true),
    ('KIRAKAI_DESDE_SALENTO_COMP', 'Kirakai desde Salento [COMPARTIDO]', 785000, 0, 0, 'COP', 'kirakai,salento,compartido', true),
    ('KIRAKAI_DESDE_FILANDIA_COMP', 'Kirakai desde Filandia [COMPARTIDO]', 567000, 0, 0, 'COP', 'kirakai,filandia,compartido', true),
    ('PIJAO_AVES_Y_COMUNIDAD_COMP', 'Pijao, aves y comunidad [COMPARTIDO]', 730000, 0, 0, 'COP', 'pijao,compartido', true),
    ('PIJAO_DESDE_FILANDIA_COMP', 'Pijao desde Filandia [COMPARTIDO]', 1313000, 0, 0, 'COP', 'pijao,filandia,compartido', true),
    ('BARISTA_POR_UN_DIA_EN_ARMENIA_COMP', 'Barista por un día en Armenia [COMPARTIDO]', 559000, 0, 0, 'COP', 'barista,armenia,compartido', true),
    ('BARISTA_POR_UN_DIA_SALENTO_FIL_COMP', 'Barista por un día Salento/Filandia [COMPARTIDO]', 493000, 0, 0, 'COP', 'barista,salento,filandia,compartido', true),
    ('METODOS_DE_FILTRADO_COMP', 'Métodos de filtrado [COMPARTIDO]', 60000, 0, 0, 'COP', 'filtrado,compartido', true),
    ('PEI_FILANDIA_SALENTO_COCORA_COMP', 'PEI Filandia Salento Cócora [COMPARTIDO]', 576000, 0, 0, 'COP', 'pei,filandia,salento,cocora,compartido', true),
    ('ARMENIA_FILANDIA_SALENTO_COCORA_COMP', 'Armenia-Filandia-Salento-Cócora [COMPARTIDO]', 1197000, 0, 0, 'COP', 'armenia,filandia,salento,cocora,compartido', true),
    ('TOUR_CASA_DE_LOS_COLIBRIES_COMP', 'Tour Casa de los Colibríes [COMPARTIDO]', 606000, 0, 0, 'COP', 'colibries,colibríes,compartido', true),
    ('SALENTO_Y_VALLE_DEL_COCORA_COMP', 'Salento y Valle del Cócora [COMPARTIDO]', 573000, 0, 0, 'COP', 'salento,cocora,compartido', true),
    ('SALENTO_Y_VALLE_DEL_COCORA_DESD_COMP', 'Salento y Valle del Cócora (desde) [COMPARTIDO]', 220000, 0, 0, 'COP', 'salento,cocora,desde,compartido', true),
    ('FILANDIA_SALENTO_Y_VALLE_DEL_CO_COMP', 'Filandia, Salento y Valle del Cócora [COMPARTIDO]', 359000, 0, 0, 'COP', 'filandia,salento,cocora,compartido', true),
    ('VISITA_GUIADA_POR_FILANDIA_COMP', 'Visita Guiada por Filandia [COMPARTIDO]', 441000, 0, 0, 'COP', 'filandia,visita guiada,compartido', true),
    ('PARQUE_DE_LA_VIDA_COMP', 'Parque de la Vida [COMPARTIDO]', 345000, 0, 0, 'COP', 'parque de la vida,compartido', true),
    ('EXCURSION_AL_VOLCAN_MACHIN_COMP', 'Excursión al Volcán Machín [COMPARTIDO]', 1285000, 0, 0, 'COP', 'volcan,machin,compartido', true),
    ('TOUR_POR_LOS_MIRADORES_DE_SALEN_COMP', 'Tour por los Miradores de Salento [COMPARTIDO]', 503000, 0, 0, 'COP', 'miradores,salento,compartido', true),
    ('TERMALES_SAN_VICENTE_PEREIRA_COMP', 'Termales San Vicente - Pereira [COMPARTIDO]', 263000, 0, 0, 'COP', 'termales,san vicente,pereira,compartido', true),
    ('TERMALES_SAN_VICENTE_SALENTO_COMP', 'Termales San Vicente - Salento [COMPARTIDO]', 789000, 0, 0, 'COP', 'termales,san vicente,salento,compartido', true),
    ('TERMALES_SAN_VICENTE_ARMENIA_COMP', 'Termales San Vicente - Armenia [COMPARTIDO]', 697000, 0, 0, 'COP', 'termales,san vicente,armenia,compartido', true),
    ('FINCA_CACAOTERA_COMP', 'Finca Cacaotera [COMPARTIDO]', 896000, 0, 0, 'COP', 'finca,cacao,compartido', true),
    ('SANTUARIO_DE_LA_PALMA_CARBONERA_COMP', 'Santuario de la Palma Carbonera [COMPARTIDO]', 990000, 0, 0, 'COP', 'santuario,carbonera,palma,compartido', true),
    ('OTUN_QUIMBAYA_COMP', 'Otún Quimbaya [COMPARTIDO]', 843000, 0, 0, 'COP', 'otun,quimbaya,compartido', true),
    ('FILANDIA_PROGRAMA_DE_CACAO_COMP', 'Filandia + Programa de Cacao [COMPARTIDO]', 731000, 0, 0, 'COP', 'filandia,cacao,compartido', true),
    ('FINCA_CAFETERA_COMP', 'Finca Cafetera [COMPARTIDO]', 192000, 0, 0, 'COP', 'finca cafetera,compartido', true),
    ('SALENTO_Y_VALLE_COCORA_CAFE_COMP', 'Salento y Valle Cócora + Café [COMPARTIDO]', 990000, 0, 0, 'COP', 'salento,cocora,cafe,compartido', true),
    ('SALENTO_Y_VALLE_COCORA_CAFE_D_COMP', 'Salento y Valle Cócora + Café (desde) [COMPARTIDO]', 1122000, 0, 0, 'COP', 'salento,cocora,cafe,desde,compartido', true),
    ('PROGRAMA_DE_CAFE_CON_TERMALES_S_COMP', 'Programa de Café con Termales [COMPARTIDO]', 971000, 0, 0, 'COP', 'cafe,termales,compartido', true),
    ('PROGRAMA_DE_TERMALES_DE_SANTA_R_COMP', 'Programa de Termales de Santa Rosa [COMPARTIDO]', 765000, 0, 0, 'COP', 'termales,santa rosa,compartido', true),
    ('PEREIRA_PROGRAMA_DE_TERMALES_DE_COMP', 'Pereira - Programa de Termales [COMPARTIDO]', 365000, 0, 0, 'COP', 'pereira,termales,compartido', true),
    ('ACAIME', 'Tour Acaime / Trekking RN Acaime (alias) [PRIVADO]', 611000, 0, 0, 'COP', 'acaime', true),
    ('COCORA', 'Valle de Cócora (alias) [PRIVADO]', 682000, 0, 0, 'COP', 'cocora', true),
    ('FILANDIA', 'Filandia (alias visita/combo) [COMPARTIDO]', 441000, 0, 0, 'COP', 'filandia', true),
    ('TERMALES', 'Termales (alias San Vicente desde Salento) [COMPARTIDO]', 789000, 0, 0, 'COP', 'termales', true),
    ('CAFE', 'Tour / Finca Café (alias) [COMPARTIDO]', 192000, 0, 0, 'COP', 'cafe', true),
    ('SALENTO', 'Citytour / Salento (alias) [COMPARTIDO]', 364000, 0, 0, 'COP', 'salento', true)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    price_per_person = EXCLUDED.price_per_person,
    transport_per_person = EXCLUDED.transport_per_person,
    restaurant_per_person = EXCLUDED.restaurant_per_person,
    currency = EXCLUDED.currency,
    keywords = EXCLUDED.keywords,
    active = EXCLUDED.active;
